import os
import sys
import rtconfig

RTT_ROOT = os.path.normpath(os.getcwd() + '/../')
from building import *

TARGET = 'rtthread-gui.' + rtconfig.TARGET_EXT

env = Environment()

Export('RTT_ROOT')
Export('rtconfig')

# prepare building environment
objs = PrepareBuilding(env, RTT_ROOT)

# build program
env.Program(TARGET, objs)

# end building
EndBuilding(TARGET)
